CREATE TABLE "SA"."PROCEDURE_INFOREC"
  (
    "PROREC_ID"   NUMBER NOT NULL ENABLE,
    "PRO_RANK"    VARCHAR2(128 BYTE),
    "PRO_ID"      NUMBER,
    "JCREC_ID"    NUMBER,
    "STATUS"      NUMBER DEFAULT 0,
    "WORK_ID"     NUMBER,
    "WORKER_NAME" VARCHAR2(30 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;