CREATE TABLE "SA"."PROCEDURE_INFO"
  (
    "PRO_ID"                NUMBER NOT NULL ENABLE,
    "PRO_NAME"              VARCHAR2(20 BYTE),
    "PRO_TYPE"              NUMBER DEFAULT 2,
    "IMAGE_NUM"             NUMBER,
    "VIDEO_TIME"            NUMBER(10,2),
    "JC_TYPE"               VARCHAR2(20 BYTE),
    "PRO_NOTE"              VARCHAR2(200 BYTE),
    "PRO_SN"                NUMBER DEFAULT 0,
    "IMAGE_TIME_DIFFERENCE" NUMBER,
    "PRO_TIME_DIFFERENCE"   NUMBER,
    "PRO_NUM"               VARCHAR2(200 BYTE),
    "SHOW_TYPE"             NUMBER DEFAULT 1,
    "WORK_ID"               NUMBER,
    "STATUS"                NUMBER DEFAULT 0,
    CONSTRAINT "PROCEDURE_INFO_PK" PRIMARY KEY ("PRO_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
COMMENT ON COLUMN "SA"."PROCEDURE_INFO"."PRO_TYPE"
IS
  '类型 0：图片 1：视频 2：都有';
  COMMENT ON COLUMN "SA"."PROCEDURE_INFO"."PRO_SN"
IS
  '顺序号：越大越靠前';
  COMMENT ON COLUMN "SA"."PROCEDURE_INFO"."SHOW_TYPE"
IS
  '1表示列表显示，2前后对比显示';
  COMMENT ON COLUMN "SA"."PROCEDURE_INFO"."WORK_ID"
IS
  '作业大类ID';
  COMMENT ON COLUMN "SA"."PROCEDURE_INFO"."STATUS"
IS
  '0：显示 1：不显示