CREATE TABLE "SA"."PROCEDURE_STEP"
  (
    "STEP_ID"       NUMBER NOT NULL ENABLE,
    "STEP_NAME"     VARCHAR2(256 BYTE),
    "PRO_ID"        NUMBER,
    "STEP_IMAGE"    VARCHAR2(256 BYTE),
    "PRO_SN"        NUMBER,
    "PRESTEP_IMAGE" VARCHAR2(256 BYTE),
    CONSTRAINT "PROCEDURE_STEP_PK" PRIMARY KEY ("STEP_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ;
COMMENT ON COLUMN "SA"."PROCEDURE_STEP"."PRO_SN"
IS
  'À≥–Ú∫≈£∫‘Ω¥Û‘Ωøø«∞';
  COMMENT ON COLUMN "SA"."PROCEDURE_STEP"."PRESTEP_IMAGE"
IS
  'Àı¬‘Õº';