CREATE TABLE "SA"."TAKE_DETAIL_REC"
  (
    "DETAIL_ID"     NUMBER NOT NULL ENABLE,
    "TYPE"          NUMBER,
    "ORDER_NUM"     NUMBER DEFAULT 0,
    "URL"           VARCHAR2(200 BYTE),
    "PRO_ID"        NUMBER,
    "STEP_ID"       NUMBER,
    "STEP_NAME"     VARCHAR2(20 BYTE),
    "STEP_IMAGE"    VARCHAR2(200 BYTE),
    "TAKE_ID"       NUMBER,
    "TAKE_NAME"     VARCHAR2(20 BYTE),
    "TAKE_TIME"     VARCHAR2(20 BYTE),
    "VIDEO_TIME"    NUMBER(10,2),
    "PREURL"        VARCHAR2(200 BYTE),
    "PRESTEP_IMAGE" VARCHAR2(200 BYTE),
    "UPLOAD_TIME"   VARCHAR2(20 BYTE),
    CONSTRAINT "TAKE_DETAIL_REC_PK" PRIMARY KEY ("DETAIL_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ENABLE ROW MOVEMENT ;
COMMENT ON COLUMN "SA"."TAKE_DETAIL_REC"."TYPE"
IS
  '类型0：图片 1：视频';
  COMMENT ON COLUMN "SA"."TAKE_DETAIL_REC"."PREURL"
IS
  '缩略图路径';
  COMMENT ON COLUMN "SA"."TAKE_DETAIL_REC"."PRESTEP_IMAGE"
IS
  '缩略图';
  COMMENT ON COLUMN "SA"."TAKE_DETAIL_REC"."UPLOAD_TIME"
IS
  '上传时间';