-- Create table
CREATE TABLE TRAIN_PLAN
  (
    "ID"       NUMBER NOT NULL ENABLE,
    "JC_NUM"   VARCHAR2(200 BYTE),
    "STRATED"  VARCHAR2(200 BYTE),
    "ENDED"    VARCHAR2(200 BYTE),
    "CJ_NUM"   VARCHAR2(200 BYTE),
    "TIME"     VARCHAR2(200 BYTE),
    "JC_CS"    VARCHAR2(200 BYTE),
    "AREAID"   NUMBER,
    "JC_STYLE" VARCHAR2(200 BYTE)
  )
  SEGMENT CREATION DEFERRED PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING TABLESPACE "USERS" ;